# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ThiagoNasc.com
email: thiagonasc@gmail.com
description: "Experiências, estudos e conteúdo interessantes (pessoais e profissionais) sobre gestão de projetos, experiência do usuário e desenvolvimento web."
baseurl: ""
url: "http://www.thiagonasc.com"
author: "Thiago Nascimento"

# Build settings
theme: minima
plugins:
  - jekyll-feed
rss: rss

#####################################################
#
# CUSTOMIZACOES THIAGONASC.COM
#
#####################################################

google_analytics: UA-30680813-1
google_analytics_ga4: G-0T15MRTY12

permalink: /:categories/:title

link:
 twitter: http://www.twitter.com/thiagonasc
 github:  http://www.github.com/thiagonasc
 facebook: https://www.facebook.com/thiagonascimentooliveira
 behance: http://www.behance.net/thiagonasc/
 slideshare:  http://www.slideshare.net/thiagonasc/
 linkedin:  http://linkedin.com/in/thiago-nascimento-oliveira/
 instagram: http://instagram.com/thiagonasc/

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
 date_format: "%b %-d, %Y"

disqus:
 shortname: thiagonasc

sass:
  sass_dir: _sass
  style: compressed